import 'package:bonvoyage/databasehelper/databasehelper.dart';
import 'package:flutter/material.dart';

class DatabaseEntryDummy extends StatefulWidget {
  const DatabaseEntryDummy({super.key});

  @override
  State<DatabaseEntryDummy> createState() => _DatabaseEntryDummyState();
}

class _DatabaseEntryDummyState extends State<DatabaseEntryDummy> {
  void syncDb() async {
    List<Map<String, dynamic>> data = [
      {
        "Id": 7020,
        "EmployeeNumber": 12909,
        "EmployeeName": "LAVANYA VADLA",
        "EmployeeType": "C",
        "JoinDate": "01\/06\/2020",
        "BirthDate": "12\/13\/1982",
        "Category": 2,
        "CategoryName": "EXECUTIVES -PHA",
        "DescCode": 35,
        "DescName": "JR. EXECUTIVE",
        "LocationCode": 207,
        "LocationName": "CORPORATE OFFICE",
        "DeptCode": 2100,
        "DeptName": "ADMINISTRATION",
        "EmailId": "Frontoffice@biologicale.com",
        "Place": "TELANGANA",
        "Sex": "F",
        "State": "TS",
        "OrgCode": "PHA",
        "DivCode": "PHA",
        "FatherOrHusbandName": "VADLA MAHESH LATE",
        "ManagerId": 6339,
        "HodId": 14683,
        "MobileNo": 9999999999,
        "ProfitCentre": 1110,
        "CostCentre": 11102101,
        "GradeCode": 2,
        "Cadre": "EXECUTIVE",
        "LevelId": "JE",
        "MprDeptCode": 4101,
        "MprDivision": "Corporate",
        "MprFunction": "Admin",
        "MprDepartment": "Admin",
        "MprLocation": "All",
        "ManagerName": "M PRAMEELA",
        "ManagerMail": "Prameela.Mantravad@biologicale.com",
        "HODName": "LAVANYA M",
        "HODMail": "Lavanya.Maligonda@biologicale.com",
      },
      {
        "Id": 6659,
        "EmployeeNumber": 6339,
        "EmployeeName": "M PRAMEELA",
        "EmployeeType": "C",
        "JoinDate": "02\/25\/2008",
        "BirthDate": "12\/01\/1972",
        "Category": 2,
        "CategoryName": "EXECUTIVES -PHA",
        "DescCode": 2,
        "DescName": "ASSISTANT MANAGER",
        "LocationCode": 207,
        "LocationName": "CORPORATE OFFICE",
        "DeptCode": 2100,
        "DeptName": "ADMINISTRATION",
        "EmailId": "Prameela.Mantravad@biologicale.com",
        "Place": "HYDERABAD",
        "Sex": "F",
        "State": "TS",
        "OrgCode": "PHA",
        "DivCode": "PHA",
        "FatherOrHusbandName": "M.K.SASTRY",
        "ManagerId": 11816,
        "HodId": 14683,
        "MobileNo": 8888888888,
        "ProfitCentre": 9001,
        "CostCentre": 90012101,
        "GradeCode": 3,
        "Cadre": "JUNIOR MANAGEMENT",
        "LevelId": "AM",
        "MprDeptCode": 4101,
        "MprDivision": "Corporate",
        "MprFunction": "Admin",
        "MprDepartment": "Admin",
        "MprLocation": "All",
        "ManagerName": "PRAVEEN KUMAR ELAVARTHY",
        "ManagerMail": "Praveen.Elavarthy@biologicale.com",
        "HODName": "LAVANYA M",
        "HODMail": "Lavanya.Maligonda@biologicale.com"
      },
      {
        "Id": 9399,
        "EmployeeNumber": 11816,
        "EmployeeName": "PRAVEEN KUMAR ELAVARTHY",
        "EmployeeType": "C",
        "JoinDate": "04\/06\/2017",
        "BirthDate": "04\/30\/1978",
        "Category": 1,
        "CategoryName": "MANAGERS -PHA",
        "DescCode": 55,
        "DescName": "ASST.GENERAL MANAGER",
        "LocationCode": 450,
        "LocationName": "BE PHARMA SHAMEERPET",
        "DeptCode": 2100,
        "DeptName": "ADMINISTRATION",
        "EmailId": "Praveen.Elavarthy@biologicale.com",
        "Place": "HYDERABAD 500 072",
        "Sex": "M",
        "State": "TS",
        "OrgCode": "PHA",
        "DivCode": "PHA",
        "FatherOrHusbandName": "E SUBRAMANYA REDDY",
        "ManagerId": 14683,
        "HodId": 14683,
        "MobileNo": 7777777777,
        "ProfitCentre": 1150,
        "CostCentre": 11502101,
        "GradeCode": 5,
        "Cadre": "SENIOR MIDDLE MANAGEMENT",
        "LevelId": "AGM",
        "MprDeptCode": 4101,
        "MprDivision": "Corporate",
        "MprFunction": "Admin",
        "MprDepartment": "Admin",
        "MprLocation": "All",
        "ManagerName": "LAVANYA M",
        "ManagerMail": "Lavanya.Maligonda@biologicale.com",
        "HODName": "LAVANYA M",
        "HODMail": "Lavanya.Maligonda@biologicale.com"
      },
      {
        "Id": 7921,
        "EmployeeNumber": 14683,
        "EmployeeName": "LAVANYA M",
        "EmployeeType": "C",
        "JoinDate": "02\/16\/2023",
        "BirthDate": "11\/04\/1977",
        "Category": 20,
        "CategoryName": "GM AND ABOVE-PHA",
        "DescCode": 35,
        "DescName": "VICE PRESIDENT",
        "LocationCode": 369,
        "LocationName": "JUBILEE HILLS OFFICE",
        "DeptCode": 2200,
        "DeptName": "HRD",
        "EmailId": "Lavanya.Maligonda@biologicale.com",
        "Place": "HYDERABAD",
        "Sex": "F",
        "State": "TS",
        "OrgCode": "PHA",
        "DivCode": "PHA",
        "FatherOrHusbandName": "G D SHANKAR RAO",
        "ManagerId": 3063,
        "HodId": 3063,
        "MobileNo": 6666666666,
        "ProfitCentre": 9001,
        "CostCentre": 90012102,
        "GradeCode": 7,
        "Cadre": "EXECUTIVE MANAGEMENT",
        "LevelId": "VP",
        "MprDeptCode": 4501,
        "MprDivision": "Corporate",
        "MprFunction": "HR",
        "MprDepartment": "HR",
        "MprLocation": "All",
        "ManagerName": "MAHIMA DATLA",
        "ManagerMail": "Girija.Ayalasomayajula@biologicale.com",
        "HODName": "MAHIMA DATLA",
        "HODMail": "Girija.Ayalasomayajula@biologicale.com"
      },
      {
        "Id": 3410,
        "EmployeeNumber": 12015,
        "EmployeeName": "SANDEEP PENMETSA",
        "EmployeeType": "C",
        "JoinDate": "09\/07\/2017",
        "BirthDate": "10\/21\/1985",
        "LeftDate": "NULL",
        "Category": 2,
        "CategoryName": "EXECUTIVES -PHA",
        "DescCode": 1,
        "DescName": "DEPUTY MANAGER",
        "LocationCode": 207,
        "LocationName": "CORPORATE OFFICE",
        "DeptCode": 75,
        "DeptName": "INFORMATION SYSTEMS",
        "EmailId": "Sandeep.Penmetsa@biologicale.com",
        "Place": "HYDERABAD 500019",
        "Sex": "M",
        "IncDate": "NULL",
        "PanGIRNumber": "NULL",
        "State": "TS",
        "OrgCode": "PHA",
        "DivCode": "PHA",
        "FatherOrHusbandName": "P V V S MURTHY",
        "ManagerId": 10814,
        "HodId": 10607,
        "MobileNo": 9866984619,
        "ProfitCentre": 9001,
        "CostCentre": 90012104,
        "GradeCode": 3,
        "Cadre": "JUNIOR MANAGEMENT",
        "LevelId": "DM",
        "MprDeptCode": 4701,
        "MprDivision": "Corporate",
        "MprFunction": "IT",
        "MprDepartment": "IT",
        "MprLocation": "All",
        "EsiEligibleDate": "NULL",
        "ModifiedDate": "NULL",
        "ManagerName": "SHRINIVAS SHARMA",
        "ManagerMail": "Shrinivas.Sharma@biologicale.com",
        "HODName": "SUDHAKAR B. VADAPALLI",
        "HODMail": "Sudhakar.Vadapalli@biologicale.com"
      },
      {
        "Id": 2085,
        "EmployeeNumber": 10814,
        "EmployeeName": "SHRINIVAS SHARMA",
        "EmployeeType": "C",
        "JoinDate": "05\/26\/2014",
        "BirthDate": "07\/04\/1985",
        "LeftDate": "NULL",
        "Category": 1,
        "CategoryName": "MANAGERS -PHA",
        "DescCode": 50,
        "DescName": "DY. GENERAL MANAGER",
        "LocationCode": 207,
        "LocationName": "CORPORATE OFFICE",
        "DeptCode": 75,
        "DeptName": "INFORMATION SYSTEMS",
        "EmailId": "Shrinivas.Sharma@biologicale.com",
        "Place": "ANDHRA PRADESH",
        "Sex": "M",
        "IncDate": "NULL",
        "PanGIRNumber": "NULL",
        "State": "TS",
        "OrgCode": "PHA",
        "DivCode": "PHA",
        "FatherOrHusbandName": "OM PRAKASH SHARMA",
        "ManagerId": 10718,
        "HodId": 10607,
        "MobileNo": 8247501713,
        "ProfitCentre": 9001,
        "CostCentre": 90012104,
        "GradeCode": 5,
        "Cadre": "SENIOR MIDDLE MANAGEMENT",
        "LevelId": "DGM",
        "MprDeptCode": 4701,
        "MprDivision": "Corporate",
        "MprFunction": "IT",
        "MprDepartment": "IT",
        "MprLocation": "All",
        "EsiEligibleDate": "NULL",
        "ModifiedDate": "NULL",
        "ManagerName": "PRAVEEN KUMAR BAHETI",
        "ManagerMail": "Praveen.Baheti@biologicale.com",
        "HODName": "SUDHAKAR B. VADAPALLI",
        "HODMail": "Sudhakar.Vadapalli@biologicale.com"
      },
      {
        "Id": 7199,
        "EmployeeNumber": 10718,
        "EmployeeName": "PRAVEEN KUMAR BAHETI",
        "EmployeeType": "C",
        "JoinDate": "01\/16\/2014",
        "BirthDate": "10\/10\/1973",
        "LeftDate": "NULL",
        "Category": 20,
        "CategoryName": "GM AND ABOVE-PHA",
        "DescCode": 35,
        "DescName": "VICE PRESIDENT",
        "LocationCode": 207,
        "LocationName": "CORPORATE OFFICE",
        "DeptCode": 75,
        "DeptName": "INFORMATION SYSTEMS",
        "EmailId": "Praveen.Baheti@biologicale.com",
        "Place": "ANDHRA PRADESH",
        "Sex": "M",
        "IncDate": "NULL",
        "PanGIRNumber": "NULL",
        "State": "TS",
        "OrgCode": "PHA",
        "DivCode": "PHA",
        "FatherOrHusbandName": "GOPI KISHAN BAHETI",
        "ManagerId": 10607,
        "HodId": 10607,
        "MobileNo": 9959698495,
        "ProfitCentre": 9001,
        "CostCentre": 90012104,
        "GradeCode": 7,
        "Cadre": "EXECUTIVE MANAGEMENT",
        "LevelId": "VP",
        "MprDeptCode": 4701,
        "MprDivision": "Corporate",
        "MprFunction": "IT",
        "MprDepartment": "IT",
        "MprLocation": "All",
        "EsiEligibleDate": "NULL",
        "ModifiedDate": "NULL",
        "ManagerName": "SUDHAKAR B. VADAPALLI",
        "ManagerMail": "Sudhakar.Vadapalli@biologicale.com",
        "HODName": "SUDHAKAR B. VADAPALLI",
        "HODMail": "Sudhakar.Vadapalli@biologicale.com"
      }
    ];
    for (Map<String, dynamic> d in data) {
      await DataBaseHelper.insertItemOneWayDom(d, "Employee");
    }
    print(DataBaseHelper.readOneWayDom("Employee"));
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    syncDb();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(),
    );
  }
}
